# This is an example configuration of MiGA-Web. Please copy this file over
# to config/settings.local.yml and configure the variables accordingly.

# Path to the folder where the projects are to be created
miga_projects: <%= ENV["HOME"] %>/miga-data

# Base URL for e-mail links (without http://)
mail_host: localhost:3000

# Name of the partial with the home page contents. If you change this setting,
# make sure that the corresponding partial exists. For example, if you change
# the value for "custom", the contents of the home page should be defined in
# "app/views/static_pages/_home_custom.html.erb".
home_contents: default

# Name of the partial with the login page contents message. If you change this
# setting, make sure that the corresponding partial exists. For example, if you
# change the value for "custom", the contents of the login message should be defined
# in "app/views/sessions/_login_custom.html.erb".
login_message: default

